; XDEBUG Extension
;; changes required restarting apache2 to reflect
;; config here could be overridden by command-line arg or Environemnt variables
[xdebug]
; zend_extension=xdebug ;; would be loaded by docker container
xdebug.mode=develop,debug
xdebug.show_local_vars=1
xdebug.log_level=3
xdebug.client_host="host.docker.internal" ;; docker ipaddress, check in compose.yml and C:\Windows\System32\drivers\etc\hosts

;; xdebug port must be mapped from host to docker container,
;; otherwise all `php` and `composer` would stuck in debugging 
;;   when `xdebug.mode` include `debug` mode but no active debugging session started by IDE --i.e. port not being listen to--
xdebug.client_port=9003   
;;  xdebug session should be started inside container
;;  if for host machine to work, ensure not to map host port 9003 to container 9003 port

;; the `composer` will be stuck if port 9003 is not being listen to 
;;   --i.e no debugging session started and no port being mapped--; 
;; this will apply to all php process and attempt to debug all script inlcuding started by command-line
xdebug.start_with_request=yes  
  ;; may provide variable to disable xdebug along with composer command `XDEBUG_MODE=off composer`
; xdebug.start_with_request=trigger  ;; run only if a request has cookie or queryString XDEBUG_TRIGGER=1


;; to test user-perspective, turn off error reporting in page
; xdebug.mode=off
; display_errors=off

;; note: these conf keys may be overriden from [ ENV, command line variable, flags ]
;;   command line [variables, flags] have the highest authority