services:
  mysql:
    image: mysql:8.0.41
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: cardeco  # db name to create/use
      MYSQL_USER: cardeco-app
      MYSQL_PASSWORD: cardeco-app
    volumes:
      - ./db/cardeco.sql:/docker-entrypoint-initdb.d/dump.sql:ro  #init db if none exist
      - cardeco-production-data:/var/lib/mysql   #
      - ./db/dump:/var/tmp/dump/  #db backup
    post_start:  # wait t seconds then backup db, remove old files and keep top n recent backup file
      - command: sh -c 'sleep 2 && mysqldump -h 127.0.0.1 -u root -ptoor cardeco --lock-all-tables | gzip > /var/tmp/dump/cardeco.db.dump.$(date --utc +"%Y-%m-%d_%H%M%S").sql.gz && cd /var/tmp/dump/ && ls -t | tail -n +6 | xargs -I {} rm -f "{}"'
        user: root
    ports:
      - "3306:3306"
    restart: always

  app:
    image: cardeco:production
    ports:
      - 0.0.0.0:8080:80   # port mapping host:container
    working_dir: /var/www/html
    environment:  #
      IS_PRODUCTION: 1
      MYSQL_HOST: mysql
      MYSQL_USER: cardeco-app
      MYSQL_PASSWORD: cardeco-app
      MYSQL_DB: cardeco
    restart: always   # auto start container on docker launch

volumes:
  cardeco-production-data: