## to addon OR update existing settings

# services:
#   # Update this to the name of the service you want to work with in your docker-compose.yml file
#   app-dev:
#     command: sleep infinity  ## keep container running, allow vscode to connect
#                              ## and stop Apache server from starting automatically in background

#     # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer 
#     # folder. Note that the path of the Dockerfile and context is relative to the *primary* 
#     # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
#     # array). The sample below assumes your primary file is in the root of your project.
#     #
#     # build:
#     #   context: .
#     #   dockerfile: .devcontainer/Dockerfile

#     # volumes:
#     # #   # Update this to wherever you want VS Code to mount the folder of your project
#     #   - ..:/workspaces:cached

#     # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
#     # cap_add:
#     #   - SYS_PTRACE
#     # security_opt:
#     #   - seccomp:unconfined


services:
  gemini-cli:
    # image: mcr.microsoft.com/devcontainers/javascript-node:24
    image: us-docker.pkg.dev/gemini-code-dev/gemini-cli/sandbox:0.36.0
    volumes:
      - ./:/workspace:cached
    working_dir: /workspace
    command: sleep infinity